spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tzry/springclouddemo.git
          basedir: springclouddemo/configServer/src/main/configDir

server:
  port: 8768  #the port on which the application runs

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

logging:
  level:
    com:
      netflix:
        discovery: 'OFF'
    org:
      springframework:
        cloud: 'DEBUG'