spring:
  application:
    name: ADMIN-CLIENT

server:
  port: 8776  #the port on which the application runs

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    registry-fetch-interval-seconds: 5

management.endpoints.web.exposure.include: "*"