spring:
  application:
    name: ZIPKIN-PRODUCER1
  zipkin:
    base-url: http://127.0.0.1:9411/
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8772  #the port on which the application runs

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/